# The best

name: Sync Files To Test Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  upload:
    name: Sync Files
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set Git Config
        run: |
          echo "${{ secrets.sftp_key }}" > key.pem
          git config git-ftp.url ${{ secrets.sftp_test_url }}
          git config git-ftp.user ${{ secrets.sftp_test_user }}
          git config git-ftp.key key.pem
          git config git-ftp.insecure "1"
          echo "::add-mask::${{ secrets.sftp_test_hostname }}"
      
      - name: Sync EntWatch Files
        run: git ftp push --verbose --auto-init --syncroot "entwatch" --remote-root "game/csgo/addons/cs2fixes/configs/entwatch/maps"

      - name: Sync Stripper Files
        run: git ftp push --verbose --auto-init --syncroot "stripper" --remote-root "game/csgo/addons/StripperCS2/maps/"

      - name: Sync Map Config Files
        run: git ftp push --verbose --auto-init --syncroot "mapcfg" --remote-root "game/csgo/cfg/cs2fixes/maps/"